name: metawavemedia
favicon: null
layout_spectrum: 0.22665
typography_spectrum: 0.46413
title: Metawave Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#77aec9'
    - '#376469'
    - '#f6fcfc'
    - '#112a38'
    - '#a28767'
  brandStrength: 0.059551341691985726
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.49036522884853184
purpose: []
